version: '2'

catalog:
  name: "oamd"
  version: "v1.6.8-1"
  minimum_rancher_version: v1.6.0
  questions:
    - variable: "API_ADDR"
      default: "0.0.0.0"
      required: false
      label: "Address where to bound the grpc API service(s)"
      type: string
    - variable: "HOST_PORT"
      default: 54567
      required: false
      label: "Port"
      type: int
    - variable: "REST_ADDR"
      default: "0.0.0.0"
      required: false
      label: "address where to bound the REST API service(s)"
      type: string
    - variable: "REST_PORT"
      default: 9090
      required: false
      label: "port where to bound the REST API service(s)"
      type: int
    - variable: "RANCHER_ADDR"
      default: "10.254.10.10"
      required: false
      label: "Rancher server address"
      type: string
    - variable: "RANCHER_PORT"
      default: 8765
      required: false
      label: "Rancher server port"
      type: int
    - variable: "RANCHER_PROJECT"
      default: "Default"
      required: true
      label: "Rancher environment name"
      type: string
    - variable: "RANCHER_STACK"
      default: "nxw-sv"
      required: true
      label: "Rancher stack name"
      type: string
    - variable: "RANCHER_AKEY"
      required: true
      label: "Rancher API access key"
      type: password
    - variable: "RANCHER_SKEY"
      required: true
      label: "Rancher API secret key"
      type: password
    - variable: "RANCHER_REQ_TOUT"
      default: "10s"
      required: false
      label: "Timeout for requests to Rancher"
      type: string
    - variable: "RANCHER_POLL_DELAY"
      default: "10s"
      required: false
      label: "Delay for polling Rancher"
      type: string
    - variable: "RANCHER_CATALOG_REMAP"
      required: false
      label: "Rancher catalog remappings"
      type: string
    - variable: LOGS_LEVEL
      label: "Logging level"
      required: false
      type: enum
      default: info
      options:
        - panic
        - fatal
        - error
        - warn
        - info
        - debug
        - trace



