version: '2'

catalog:
  name: "update-manager"
  version: "v0.0.24-2"
  minimum_rancher_version: v1.6.0
  questions:
    - variable: "API_ADDR"
      default: "0.0.0.0"
      required: false
      label: "Address where to bound the API service"
      type: string
    - variable: "HOST_PORT"
      default: 54567
      required: false
      label: "Port"
      type: int
    - variable: "RANCHER_ADDR"
      default: "127.0.0.1"
      required: false
      label: "Rancher server address"
      type: string
    - variable: "RANCHER_PORT"
      default: 8080
      required: false
      label: "Rancher server port"
      type: int
    - variable: "RANCHER_PROJECT"
      default: "Default"
      required: true
      label: "Rancher environment name"
      type: string
    - variable: "RANCHER_STACK"
      default: "nxw-sv"
      required: true
      label: "Rancher stack name"
      type: string
    - variable: "RANCHER_AKEY"
      required: true
      label: "Rancher API access key"
      type: password
    - variable: "RANCHER_SKEY"
      required: true
      label: "Rancher API secret key"
      type: password
    - variable: "RANCHER_REQ_TOUT"
      default: "10s"
      required: false
      label: "Timeout for requests to Rancher"
      type: string
    - variable: "RANCHER_POLL_DELAY"
      default: "10s"
      required: false
      label: "Delay for polling Rancher"
      type: string
    - variable: LOG_LEVEL
      label: "Logging level"
      required: true
      type: enum
      default: info
      options:
        - panic
        - fatal
        - error
        - warn
        - info
        - debug
        - trace

